//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeStoreMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BikeStoreEntities : DbContext
    {
        public BikeStoreEntities()
            : base("name=BikeStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_category> tbl_category { get; set; }
        public virtual DbSet<tbl_colour> tbl_colour { get; set; }
        public virtual DbSet<tbl_description> tbl_description { get; set; }
        public virtual DbSet<tbl_model> tbl_model { get; set; }
        public virtual DbSet<tbl_product> tbl_product { get; set; }
        public virtual DbSet<tbl_size> tbl_size { get; set; }
        public virtual DbSet<tbl_sub_category> tbl_sub_category { get; set; }
    }
}
