//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeStoreMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int proID { get; set; }
        public string productCode { get; set; }
        public string productName { get; set; }
        public int categoryID { get; set; }
        public int subCategoryID { get; set; }
        public int modelID { get; set; }
        public decimal price { get; set; }
        public Nullable<int> colourID { get; set; }
        public Nullable<int> sizeID { get; set; }
        public int descriptionID { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
        public virtual tbl_colour tbl_colour { get; set; }
        public virtual tbl_description tbl_description { get; set; }
        public virtual tbl_model tbl_model { get; set; }
        public virtual tbl_size tbl_size { get; set; }
        public virtual tbl_sub_category tbl_sub_category { get; set; }
    }
}
